title: The Nam Dang Blogs
email: nam.dang.141@my.csun.edu
description: >-
   This that Namdingo blog
   Welcome to my hood
baseurl: ""
url: "https://namdang223.github.io"
twitter_username: jekyllrb
github_username: jekyll

#BUild settings
theme: minima
plugins:
        - jekyll-feed
