title: The Nam Dang Blogs
email: nam.dang.141@my.csun.edu
description: >-
        This that Nam Dang Blog. Here is where I post updates of what I learn here at Cal State University of Northridge
   
baseurl: ""
url: "https://namdang223.github.io"
twitter_username: jekyllrb
github_username: jekyll

#BUild settings
theme: minima
plugins:
        - jekyll-feed
